/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Point;
import java.awt.Rectangle;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author bethoveen
 */
public class Details extends javax.swing.JFrame {

    /**
     * Creates new form SignUpForm
     */
    public Details(String Title,String ImgURL ,String Brief) {
        initComponents();
        GUIManager.Instance().setDynamicSize(this,jPanel1); 
        Title0.setText(Title);
        //BigImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(ImgURL))); // NOI18N Image quality is bad so it's diabled for the prototyping , on visiting site, more pictures should be supplied
        Info1.setText(Brief.split("-")[0]);
        Info2.setText(Brief.split("-")[1]);
        Info3.setText(Brief.split("-")[2]);
        Info4.setText(Brief.split("-")[3]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Container = new javax.swing.JPanel();
        OverView = new javax.swing.JButton();
        Title0 = new javax.swing.JLabel();
        Title1 = new javax.swing.JLabel();
        Info1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Title2 = new javax.swing.JLabel();
        Info2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Title3 = new javax.swing.JLabel();
        Info3 = new javax.swing.JLabel();
        Info4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        FrontPanel = new javax.swing.JLabel();
        ButtonText = new javax.swing.JLabel();
        Back2 = new javax.swing.JButton();
        BigImage = new javax.swing.JLabel();
        BKG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 920));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1100, 1300));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setOpaque(false);
        Container.setLayout(null);

        OverView.setBackground(new java.awt.Color(255, 255, 255));
        OverView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DetailsIcons/Button (1).png"))); // NOI18N
        OverView.setBorder(null);
        OverView.setContentAreaFilled(false);
        OverView.setFocusCycleRoot(true);
        OverView.setMultiClickThreshhold(1L);
        OverView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OverViewMouseClicked(evt);
            }
        });
        Container.add(OverView);
        OverView.setBounds(400, 0, 170, 70);

        Title0.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        Title0.setForeground(new java.awt.Color(102, 102, 102));
        Title0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title0.setText("Title");
        Container.add(Title0);
        Title0.setBounds(380, 50, 200, 40);

        Title1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(102, 102, 102));
        Title1.setText("Artist/Manifacturer");
        Container.add(Title1);
        Title1.setBounds(60, 100, 270, 40);

        Info1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Info1.setForeground(new java.awt.Color(0, 0, 0));
        Info1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Info1.setText("dsadashdhashdhu  hfadsh asd kuayeguwi gfu weuygf yuqewgf uygwequ fy wgfey yuqwegf uygwef yugweuf");
        Info1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Info1.setAutoscrolls(true);
        Info1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Container.add(Info1);
        Info1.setBounds(60, 140, 850, 40);

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        Container.add(jSeparator1);
        jSeparator1.setBounds(160, 190, 620, 10);

        Title2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        Title2.setForeground(new java.awt.Color(102, 102, 102));
        Title2.setText("Size");
        Container.add(Title2);
        Title2.setBounds(50, 210, 80, 40);

        Info2.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Info2.setForeground(new java.awt.Color(0, 0, 0));
        Info2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Info2.setText("dsadashdhashdhu  hfadsh asd kuayeguwi gfu weuygf yuqewgf uygwequ fy wgfey yuqwegf uygwef yugweuf");
        Info2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Info2.setAutoscrolls(true);
        Info2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Container.add(Info2);
        Info2.setBounds(50, 250, 850, 40);

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        Container.add(jSeparator2);
        jSeparator2.setBounds(150, 300, 620, 10);

        Title3.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        Title3.setForeground(new java.awt.Color(102, 102, 102));
        Title3.setText("Brief");
        Container.add(Title3);
        Title3.setBounds(50, 320, 80, 40);

        Info3.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Info3.setForeground(new java.awt.Color(0, 0, 0));
        Info3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Info3.setText("dsadashdhashdhu  hfadsh asd kuayeguwi gfu weuygf yuqewgf uygwequ fy wgfey yuqwegf uygwef yugweuf");
        Info3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Info3.setAutoscrolls(true);
        Info3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Container.add(Info3);
        Info3.setBounds(50, 360, 850, 40);

        Info4.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Info4.setForeground(new java.awt.Color(0, 0, 0));
        Info4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Info4.setText("dsadashdhashdhu  hfadsh asd kuayeguwi gfu weuygf yuqewgf uygwequ fy wgfey yuqwegf uygwef yugweuf");
        Info4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Info4.setAutoscrolls(true);
        Info4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Container.add(Info4);
        Info4.setBounds(50, 420, 850, 40);

        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        Container.add(jSeparator4);
        jSeparator4.setBounds(150, 520, 620, 10);

        FrontPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DetailsIcons/FrontPanel.png"))); // NOI18N
        Container.add(FrontPanel);
        FrontPanel.setBounds(0, 20, 940, 587);

        ButtonText.setText("jLabel1");
        Container.add(ButtonText);
        ButtonText.setBounds(50, 110, 130, 60);

        jPanel1.add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, 940, 610));

        Back2.setBackground(new java.awt.Color(0, 0, 0));
        Back2.setForeground(new java.awt.Color(0, 0, 0));
        Back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/folder/BackButton.png"))); // NOI18N
        Back2.setBorder(null);
        Back2.setBorderPainted(false);
        Back2.setContentAreaFilled(false);
        Back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back2MouseClicked(evt);
            }
        });
        Back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back2ActionPerformed(evt);
            }
        });
        jPanel1.add(Back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 50, 60));

        BigImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/DetailsIcons/BigImage.png"))); // NOI18N
        jPanel1.add(BigImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 940, 820));

        BKG.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        BKG.setForeground(new java.awt.Color(153, 153, 153));
        BKG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BKG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Signing/Rectangle 3 (1).png"))); // NOI18N
        jPanel1.add(BKG, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 940, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OverViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OverViewMouseClicked
        // TODO add your handling code here:
        System.out.println("Swiping");
        Point DefaultPosition = new Point(10,720);
        Point OpenedPosition = new Point(10,220);
        //Container.setLocation(DefaultPosition);
        GUIManager.Instance().SwipePanel(Container,DefaultPosition,OpenedPosition);
    }//GEN-LAST:event_OverViewMouseClicked

    private void Back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back2MouseClicked
        // TODO add your handling code here:
        Backend.ArtPiecePage.Instance().backButtom(this, new Explore());
    }//GEN-LAST:event_Back2MouseClicked

    private void Back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Back2ActionPerformed
            

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BKG;
    private javax.swing.JButton Back;
    private javax.swing.JButton Back1;
    private javax.swing.JButton Back2;
    private javax.swing.JLabel BigImage;
    private javax.swing.JLabel ButtonText;
    private javax.swing.JPanel Container;
    private javax.swing.JLabel FrontPanel;
    private javax.swing.JLabel Info1;
    private javax.swing.JLabel Info2;
    private javax.swing.JLabel Info3;
    private javax.swing.JLabel Info4;
    private javax.swing.JButton OverView;
    private javax.swing.JLabel Title0;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel Title3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
